services:
  neohub:
    image: "ghcr.io/brianhumlicek/neohub:latest"
    container_name: NeoHub
    ports:
      - "5181:8080"     # HTTP Web UI
      - "7013:8443"     # HTTPS Web UI
      - "3072:3072"     # Panel ITv2 connection
    volumes:
      - NeoHub:/app/persist
    restart: unless-stopped

volumes:
  NeoHub:
